# -*- coding: utf-8 -*-

SONGS = [
    {
        "id": 1,
        "title": '群青 (Gunjou)',
        "artist": 'YOASOBI',
        "genre": 'jpop',
        "moods": ['energy', 'emotional'],
        "description": '好きなものを好きと言うことの葛藤と喜びを歌う曲。今日のあなたの一歩は、間違いなく輝く未来へと繋がっています。恐れずに進みましょう！',
        "lucky_item": 'お気に入りのスケッチブック',
        "lucky_color": 'ウルトラマリン（鮮やかな青）',
        "color_code": '#002fa7',
        "lyrics_snippet": '知らず知らず隠してた 本当の声を響かせてよ、さあ',
        "youtube_query": 'YOASOBI 群青',
    },
    {
        "id": 2,
        "title": 'きらり (Kirari)',
        "artist": '藤井風',
        "genre": 'jpop',
        "moods": ['happy', 'calm'],
        "description": '日常の何気ないきらめきを捉えるポップソング。今日はフットワークを軽くして、新しい発見を楽しんでください。素敵な出会いが待っています。',
        "lucky_item": 'サングラス',
        "lucky_color": 'イエローゴールド',
        "color_code": '#ffd700',
        "lyrics_snippet": '荒れ狂う季節の中を二人は一人きり さらりと さらりと 逃げのびる',
        "youtube_query": '藤井風 きらり',
    },
    {
        "id": 3,
        "title": '怪獣の花唄',
        "artist": 'Vaundy',
        "genre": 'jpop',
        "moods": ['energy', 'happy'],
        "description": '心震えるメロディと疾走感が魅力。胸の中にある眠っていた情熱を呼び覚ます日です。大声でハミングしながら、元気よく進みましょう！',
        "lucky_item": 'スニーカー',
        "lucky_color": 'コーラルレッド',
        "color_code": '#ff7f50',
        "lyrics_snippet": '騒がしい街のどこかで、僕らはずっと歌を歌っている',
        "youtube_query": 'Vaundy 怪獣の花唄',
    },
    {
        "id": 4,
        "title": 'One Last Kiss',
        "artist": '宇多田ヒカル',
        "genre": 'jpop',
        "moods": ['emotional', 'calm'],
        "description": '深くエモーショナルで美しいメロディ。大切な記憶や人への愛おしさが増す日です。過去を愛し、今この瞬間を噛み締めましょう。',
        "lucky_item": 'アロマキャンドル',
        "lucky_color": 'ディープパープル',
        "color_code": '#4b0082',
        "lyrics_snippet": '初めてのルーブルは なんてことはなかったわ 私だけのモナリザ もうとっくに出会ってたから',
        "youtube_query": '宇多田ヒカル One Last Kiss',
    },
    {
        "id": 5,
        "title": 'Subtitle',
        "artist": 'Official髭男dism',
        "genre": 'jpop',
        "moods": ['emotional', 'focus'],
        "description": '言葉の奥にある温かい想いを伝えるバラード。身近な人に感謝や温かい想いを伝えるのに最適な日です。不器用でも言葉にしてみて。',
        "lucky_item": 'マフラーまたはストール',
        "lucky_color": 'スノーホワイト',
        "color_code": '#fffafa',
        "lyrics_snippet": '凍りついた心には太陽を そして僕の心には君を',
        "youtube_query": 'Official髭男dism Subtitle',
    },
    {
        "id": 6,
        "title": 'ダンスホール',
        "artist": 'Mrs. GREEN APPLE',
        "genre": 'jpop',
        "moods": ['happy', 'energy'],
        "description": 'どんな日もダンスホールのように楽しもうというポジティブソング。今日がどんなに忙しくても、楽しむ心を忘れなければ素晴らしい一日になります！',
        "lucky_item": '手鏡',
        "lucky_color": 'サンシャインオレンジ',
        "color_code": '#ff9e2c',
        "lyrics_snippet": 'いつだって大丈夫、僕らは何処へでも行ける',
        "youtube_query": 'Mrs GREEN APPLE ダンスホール',
    },
    {
        "id": 7,
        "title": 'ドライフラワー',
        "artist": '優里',
        "genre": 'jpop',
        "moods": ['emotional'],
        "description": 'すれ違う心と切ない愛の余韻を歌うラブソング。過去の想い出を整理し、新しい一歩を踏み出すのに適した日です。自分自身の成長を感じられるでしょう。',
        "lucky_item": 'ドライフラワーの一輪挿し',
        "lucky_color": 'アンティークベージュ',
        "color_code": '#c8b195',
        "lyrics_snippet": '声も顔も不器用なとこも 全部全部嫌いじゃないの',
        "youtube_query": '優里 ドライフラワー',
    },
    {
        "id": 8,
        "title": '新時代',
        "artist": 'Ado',
        "genre": 'jpop',
        "moods": ['energy', 'happy'],
        "description": '力強いボーカルと圧倒的な疾走感。新しいことに挑戦するエネルギーに満ちあふれています。古い殻を破り、あなたの新時代を切り開きましょう！',
        "lucky_item": 'ワイヤレススピーカー',
        "lucky_color": 'ネオンピンク',
        "color_code": '#ff007f',
        "lyrics_snippet": '新時代はこの未来だ 世界中全部変えてしまえば',
        "youtube_query": 'Ado 新時代',
    },
    {
        "id": 9,
        "title": 'KICK BACK',
        "artist": '米津玄師',
        "genre": 'jpop',
        "moods": ['energy'],
        "description": '圧倒的なパッションとカオスな疾走感。困難な状況を力技で突破できる日です。限界を恐れず、全力で突き進みましょう！',
        "lucky_item": 'エナジードリンク',
        "lucky_color": 'チェンソーイエロー',
        "color_code": '#e6b422',
        "lyrics_snippet": '努力 未来 A BEAUTIFUL STAR なんか幸せになりたい',
        "youtube_query": '米津玄師 KICK BACK',
    },
    {
        "id": 10,
        "title": '恋',
        "artist": '星野源',
        "genre": 'jpop',
        "moods": ['happy'],
        "description": '軽快なイエローミュージックのビート。今日出会う人々と自然と笑顔で繋がれる一日。日常の中に隠れたワクワクを楽しんでください。',
        "lucky_item": 'お気に入りの靴下',
        "lucky_color": 'サニーイエロー',
        "color_code": '#ffeb3b',
        "lyrics_snippet": '夫婦を超えてゆけ 二人を超えてゆけ 一人を超えてゆけ',
        "youtube_query": '星野源 恋',
    },
    {
        "id": 11,
        "title": 'マリーゴールド',
        "artist": 'あいみょん',
        "genre": 'jpop',
        "moods": ['happy', 'calm'],
        "description": 'ノスタルジックで温かいメロディ。大切な人との何気ない瞬間が愛おしく感じられる日。夕暮れ時の散歩が幸運を呼び込みます。',
        "lucky_item": '麦わら帽子',
        "lucky_color": 'マリーゴールドオレンジ',
        "color_code": '#f58220',
        "lyrics_snippet": '麦わらの帽子の君が 揺れたマリーゴールドに似てる',
        "youtube_query": 'あいみょん マリーゴールド',
    },
    {
        "id": 12,
        "title": '水平線',
        "artist": 'back number',
        "genre": 'jpop',
        "moods": ['emotional', 'calm'],
        "description": '悲しみや痛みに寄り添い、静かに肯定してくれるバラード。うまくいかないことがあっても、それはあなたが懸命に生きている証拠です。優しく自分を労わって。',
        "lucky_item": 'ハンカチ',
        "lucky_color": 'ホライズンブルー',
        "color_code": '#87ceeb',
        "lyrics_snippet": '歓声と拍手の中に 誰かの悲鳴が隠れている',
        "youtube_query": 'back number 水平線',
    },
    {
        "id": 13,
        "title": '白日',
        "artist": 'King Gnu',
        "genre": 'jpop',
        "moods": ['emotional', 'focus'],
        "description": '冬の冷たさと美しさを感じさせる静と動のコントラスト。過去の過ちを許し、今日からまた新しくやり長す準備が整う日です。冷静な自己対話を。',
        "lucky_item": '温かい紅茶',
        "lucky_color": 'スノーグレー',
        "color_code": '#d3d3d3',
        "lyrics_snippet": '時には誰もが知らず知らずのうちに 誰かを傷つけてしまったり',
        "youtube_query": 'King Gnu 白日',
    },
    {
        "id": 14,
        "title": 'チェリー',
        "artist": 'スピッツ',
        "genre": 'jpop',
        "moods": ['happy', 'calm'],
        "description": '何年経っても色あせない爽やかなポップス。初心に立ち返ることで、新しいインスピレーションが得られる日。新しい出会いや挑戦を恐れずに。',
        "lucky_item": 'さくらんぼのデザインの小物',
        "lucky_color": 'チェリーピンク',
        "color_code": '#e30030',
        "lyrics_snippet": '「愛してる」の響きだけで 強くなれる気がしたよ',
        "youtube_query": 'スピッツ チェリー',
    },
    {
        "id": 15,
        "title": 'First Love',
        "artist": '宇多田ヒカル',
        "genre": 'jpop',
        "moods": ['emotional'],
        "description": '切なくも美しい、不朽の名作ラブバラード。古い恋や青春の記憶をそっと思い出すような、センチメンタルで心温まる時間が訪れます。',
        "lucky_item": '古い手帳',
        "lucky_color": 'アメジストパープル',
        "color_code": '#9966cc',
        "lyrics_snippet": 'You are always gonna be my love いつか誰かとまた恋に落ちても',
        "youtube_query": '宇多田ヒカル First Love',
    },
    {
        "id": 16,
        "title": '愛にできることはまだあるかい',
        "artist": 'RADWIMPS',
        "genre": 'jpop',
        "moods": ['emotional', 'focus'],
        "description": '世界のために自分ができることを問いかける壮大なテーマ。大切な誰かを守るために、勇気を出して行動を起こせる日です。あなたの想いは必ず届きます。',
        "lucky_item": '折りたたみ傘',
        "lucky_color": 'クリアブルー',
        "color_code": '#70a6ff',
        "lyrics_snippet": '愛にできることはまだあるかい 僕にできることはまだあるかい',
        "youtube_query": 'RADWIMPS 愛にできることはまだあるかい',
    },
    {
        "id": 17,
        "title": '夜に駆ける',
        "artist": 'YOASOBI',
        "genre": 'jpop',
        "moods": ['energy', 'emotional'],
        "description": '疾走感あふれるメロディとどこか儚い世界観。めまぐるしい日常の中で、自分のインスピレーションが冴え渡る日。夜の散歩がアイデアを呼びます。',
        "lucky_item": 'お気に入りのヘアアクセサリー',
        "lucky_color": 'ミッドナイトネイビー',
        "color_code": '#191970',
        "lyrics_snippet": '沈むように溶けてゆくように 二人だけの空が広がる夜に',
        "youtube_query": 'YOASOBI 夜に駆ける',
    },
    {
        "id": 18,
        "title": 'Lemon',
        "artist": '米津玄師',
        "genre": 'jpop',
        "moods": ['emotional'],
        "description": '失ったものへの深い愛と追悼の歌。悲しみを受け入れることで、本当に大切なものが何かを再確認できる日です。静かに自分を労わってあげてください。',
        "lucky_item": 'レモンの香りのアロマ',
        "lucky_color": 'レモンイエロー',
        "color_code": '#fff352',
        "lyrics_snippet": '夢ならばどれほどよかったでしょう 未だにあなたのことを夢にみる',
        "youtube_query": '米津玄師 Lemon',
    },
    {
        "id": 19,
        "title": '君はロックを聴かない',
        "artist": 'あいみょん',
        "genre": 'jpop',
        "moods": ['happy', 'energy'],
        "description": '好きなものを共有したい熱い想いを歌う青春ソング。自分の好きな趣味や情熱を、誰かに語ってみると親密な関係が築ける日です。',
        "lucky_item": 'レコード型コースター',
        "lucky_color": 'オールドウッドブラウン',
        "color_code": '#8b4513',
        "lyrics_snippet": '君はロックを聴かないと思いながら 少しでも僕に近づいてほしくて',
        "youtube_query": 'あいみょん 君はロックを聴かない',
    },
    {
        "id": 20,
        "title": '青と夏',
        "artist": 'Mrs. GREEN APPLE',
        "genre": 'jpop',
        "moods": ['energy', 'happy'],
        "description": '眩しい太陽と青春のきらめきが詰まった爽快ロック。あなたの主役の夏（今日）が始まります！全力で今を楽しんでいきましょう！',
        "lucky_item": 'ラムネボトル',
        "lucky_color": 'スカイブルー',
        "color_code": '#00bfff',
        "lyrics_snippet": '涼しい風が吹く 青と夏が始まった',
        "youtube_query": 'Mrs GREEN APPLE 青と夏',
    },
    {
        "id": 21,
        "title": 'Dynamite',
        "artist": 'BTS',
        "genre": 'kpop',
        "moods": ['happy', 'energy'],
        "description": '弾けるようなビート and 爽快なメロディ。今日は気分を最高潮にして、やりたいことに飛び込んでみて！あなたの笑顔が最高のラッキーを引き寄せます。',
        "lucky_item": 'ワイヤレスイヤホン',
        "lucky_color": 'パステルピンク',
        "color_code": '#ffd1dc',
        "lyrics_snippet": 'Shining through the city with a little funk and soul / So light it up like dynamite',
        "youtube_query": 'BTS Dynamite',
    },
    {
        "id": 22,
        "title": 'Ditto',
        "artist": 'NewJeans',
        "genre": 'kpop',
        "moods": ['calm', 'emotional'],
        "description": 'ノスタルジックで心地よいクラブビート。今日のあなたを優しく包み込むような、穏やかでセンチメンタルな時間を提供します。',
        "lucky_item": 'ヘッドホン',
        "lucky_color": 'チェリーグレー',
        "color_code": '#8b8589',
        "lyrics_snippet": "Stay in the middle / Like you a little / Don't want no riddle",
        "youtube_query": 'NewJeans Ditto',
    },
    {
        "id": 23,
        "title": 'How You Like That',
        "artist": 'BLACKPINK',
        "genre": 'kpop',
        "moods": ['energy', 'happy'],
        "description": '強烈なビートと圧倒的なカリスマ性。自信に満ちあふれ、限界を突破できるパワフルな一日になります！強気で行きましょう。',
        "lucky_item": 'レザーのパスケース',
        "lucky_color": 'マゼンタブラック',
        "color_code": '#2b001a',
        "lyrics_snippet": 'Now look at you, now look at me / How you like that',
        "youtube_query": 'BLACKPINK How You Like That',
    },
    {
        "id": 24,
        "title": 'Butter',
        "artist": 'BTS',
        "genre": 'kpop',
        "moods": ['happy', 'energy'],
        "description": '滑らかでとろけるようなポップソング。あなたの魅力が周囲にスムーズに伝わり、物事がすいすいと進む日です。自信を持って微笑んで！',
        "lucky_item": 'トースト（バター乗せ）',
        "lucky_color": 'バターイエロー',
        "color_code": '#fffdc2',
        "lyrics_snippet": 'Smooth like butter, like a criminal undercover',
        "youtube_query": 'BTS Butter',
    },
    {
        "id": 25,
        "title": 'Hype Boy',
        "artist": 'NewJeans',
        "genre": 'kpop',
        "moods": ['happy', 'calm'],
        "description": 'さわやかで中毒性の高いY2Kサウンド。心躍るような小さなサプライズが期待できる日。少し背伸びしたファッションが吉です。',
        "lucky_item": 'カラフルなヘアピン',
        "lucky_color": 'アクアブルー',
        "color_code": '#00ffff',
        "lyrics_snippet": "Cause I know what you like boy / You're my hype boy",
        "youtube_query": 'NewJeans Hype Boy',
    },
    {
        "id": 26,
        "title": 'DDU-DU DDU-DU',
        "artist": 'BLACKPINK',
        "genre": 'kpop',
        "moods": ['energy'],
        "description": '圧倒的なパワーとトラップビート。自分の軸をしっかり持って、他人の意見に惑わされずに進むべき日。あなたの強い眼差しが運を開きます。',
        "lucky_item": 'スタッズ付きの小物',
        "lucky_color": 'ディープブラック',
        "color_code": '#0a0a0a',
        "lyrics_snippet": 'Hit you with that ddu-du ddu-du du',
        "youtube_query": 'BLACKPINK DDU-DU DDU-DU',
    },
    {
        "id": 27,
        "title": 'TT',
        "artist": 'TWICE',
        "genre": 'kpop',
        "moods": ['happy', 'energy'],
        "description": '世界を虜にしたポップでキュートなダンス曲。素直になれない可愛らしい感情を抱えつつも、今日は愛嬌たっぷりに過ごすと周囲から助けが得られます。',
        "lucky_item": 'キャンディ',
        "lucky_color": 'パステルパープル',
        "color_code": '#dfb5f2',
        "lyrics_snippet": "I'm like TT, Just like TT / Tell me that you'd be my baby",
        "youtube_query": 'TWICE TT',
    },
    {
        "id": 28,
        "title": 'LOVE DIVE',
        "artist": 'IVE',
        "genre": 'kpop',
        "moods": ['happy', 'focus'],
        "description": '魅惑的でミステリアスなダークポップ。自分の直感を信じて深く深く物事にダイブするのに適した日。探究心が幸運の鍵となります。',
        "lucky_item": '手鏡（ラウンド型）',
        "lucky_color": 'ディープオシャンブルー',
        "color_code": '#004b87',
        "lyrics_snippet": "Woo lalalalalalala / Yeah, it's a love dive",
        "youtube_query": 'IVE LOVE DIVE',
    },
    {
        "id": 29,
        "title": 'ANTIFRAGILE',
        "artist": 'LE SSERAFIM',
        "genre": 'kpop',
        "moods": ['energy'],
        "description": '試練やストレスをバネにしてさらに強くなる応援歌。今日受ける厳しいフィードバックも、あなたを成長させる燃料になります。打たれ強く進みましょう！',
        "lucky_item": 'プロテインシェイカー',
        "lucky_color": 'クロームシルバー',
        "color_code": '#e5e4e2',
        "lyrics_snippet": 'Anti-ti-ti-ti fragile fragile',
        "youtube_query": 'LE SSERAFIM ANTIFRAGILE',
    },
    {
        "id": 30,
        "title": 'Super',
        "artist": 'SEVENTEEN',
        "genre": 'kpop',
        "moods": ['energy', 'focus'],
        "description": '限界を知らないエネルギーと圧倒的な群舞を感じさせる曲。まるで孫悟空のように、どんな困難も仲間と共に飛び越えていける強気な一日になります。',
        "lucky_item": '赤いブレスレット',
        "lucky_color": 'チャイニーズレッド',
        "color_code": '#de2910',
        "lyrics_snippet": 'I love my team, I love my crew / 走り続けよう',
        "youtube_query": 'SEVENTEEN Super',
    },
    {
        "id": 31,
        "title": 'S-Class',
        "artist": 'Stray Kids',
        "genre": 'kpop',
        "moods": ['energy'],
        "description": '独自の個性と特異なサウンド。あなたが誰とも違う特別な存在であることを思い出させてくれる曲。自分だけのこだわりを強く持ちましょう。',
        "lucky_item": 'シルバーアクセサリー',
        "lucky_color": 'グリッターシルバー',
        "color_code": '#e6e6fa',
        "lyrics_snippet": '最上級のクラス、誰も真似できない星',
        "youtube_query": 'Stray Kids S-Class',
    },
    {
        "id": 32,
        "title": 'LILAC',
        "artist": 'IU',
        "genre": 'kpop',
        "moods": ['happy', 'calm'],
        "description": '青春の終わりと新しい始まりを祝うような爽やかな春の曲。大切な思い出に感謝しつつ、軽やかに新しいステージへ踏み出せる幸運な一日です。',
        "lucky_item": 'ライラックの花（または花のしおり）',
        "lucky_color": 'ライラックパープル',
        "color_code": '#c8a2c8',
        "lyrics_snippet": 'Love me only till this spring / Oh LILAC',
        "youtube_query": 'IU LILAC',
    },
    {
        "id": 33,
        "title": 'Cupid',
        "artist": 'FIFTY FIFTY',
        "genre": 'kpop',
        "moods": ['happy', 'calm'],
        "description": '甘くレトロなドリームポップ。キューピッドに頼らずとも、あなた自身の行動が素晴らしい恋愛や対人関係を引き寄せるでしょう。楽観的に過ごして。',
        "lucky_item": 'お花のチャーム',
        "lucky_color": 'ピーチピンク',
        "color_code": '#ffc0cb',
        "lyrics_snippet": "I gave a second chance to Cupid / Now I'm left here feeling stupid",
        "youtube_query": 'FIFTY FIFTY Cupid',
    },
    {
        "id": 34,
        "title": 'Next Level',
        "artist": 'aespa',
        "genre": 'kpop',
        "moods": ['energy', 'focus'],
        "description": 'メタバースと未来的なグルーヴ。次元を超えるほどの進化を遂げる日。目標を一段上の「ネクストレベル」に設定して取り組むと大成功します。',
        "lucky_item": 'スマートウォッチ',
        "lucky_color": 'ネオンパープル',
        "color_code": '#8a2be2',
        "lyrics_snippet": "I'm on the next level / 開く門を見据えて",
        "youtube_query": 'aespa Next Level',
    },
    {
        "id": 35,
        "title": 'Fancy',
        "artist": 'TWICE',
        "genre": 'kpop',
        "moods": ['happy', 'energy'],
        "description": '大胆でスタイリッシュな愛の告白ソング。自分の好きな人やモノに対して、正直に「好き！」と表現することで、関係が急接近する一日です。',
        "lucky_item": '香水',
        "lucky_color": 'ローズゴールド',
        "color_code": '#b76e79',
        "lyrics_snippet": 'FANCY YOU / 誰が先に好きになろうと関係ない',
        "youtube_query": 'TWICE Fancy',
    },
    {
        "id": 36,
        "title": 'Psycho',
        "artist": 'Red Velvet',
        "genre": 'kpop',
        "moods": ['emotional', 'calm'],
        "description": '優雅で少し影のある美しいR&B調ポップ。他人に理解されなくても、自分たちの世界やスタイルを深く愛し、貫くことで心が安定します。',
        "lucky_item": 'ダークチョコレート',
        "lucky_color": 'ベルベットワインレッド',
        "color_code": '#58111a',
        "lyrics_snippet": "You got me feeling like a psycho / People say we're crazy",
        "youtube_query": 'Red Velvet Psycho',
    },
    {
        "id": 37,
        "title": 'BANG BANG BANG',
        "artist": 'BIGBANG',
        "genre": 'kpop',
        "moods": ['energy'],
        "description": '爆発的な狂気とエネルギー。フェスティバルのように盛り上がるエネルギッシュな日。溜まったストレスを一気に発散するアクションが吉！',
        "lucky_item": '炭酸入浴剤',
        "lucky_color": 'クリムゾンオレンジ',
        "color_code": '#ff4500',
        "lyrics_snippet": 'パンヤ パンヤ パンヤ / 弾けるように踊れ',
        "youtube_query": 'BIGBANG BANG BANG BANG',
    },
    {
        "id": 38,
        "title": 'Gangnam Style',
        "artist": 'PSY',
        "genre": 'kpop',
        "moods": ['energy', 'happy'],
        "description": 'ユーモアと爆発力にあふれた世界的大ヒット曲。常識に囚われず、思い切り自分を解放して楽しむことで、周りを巻き込むポジティブな嵐を起こせます。',
        "lucky_item": '面白いスタンプ',
        "lucky_color": 'サンシャインイエロー',
        "color_code": '#ffd800',
        "lyrics_snippet": 'Oppa is Gangnam style / えーい、セクシーレディース',
        "youtube_query": 'PSY Gangnam Style',
    },
    {
        "id": 39,
        "title": 'OMG',
        "artist": 'NewJeans',
        "genre": 'kpop',
        "moods": ['happy', 'calm'],
        "description": 'バウンシーなヒップホップのリズムと甘いボーカル。予期せぬラッキーや人からの親切に「Oh my god!」と驚くような嬉しいハプニングの予感。',
        "lucky_item": 'ぬいぐるみキーホルダー',
        "lucky_color": 'ミントブルー',
        "color_code": '#add8e6',
        "lyrics_snippet": 'Oh my, oh my God / 予想してた通りね',
        "youtube_query": 'NewJeans OMG',
    },
    {
        "id": 40,
        "title": 'I AM',
        "artist": 'IVE',
        "genre": 'kpop',
        "moods": ['energy', 'happy'],
        "description": '高揚感に満ちたメロディと「自分らしく輝く」ことを歌う応援歌。誰かの真似ではなく、あなただけの美しい人生の軌跡を描いていきましょう！',
        "lucky_item": 'お気に入りの靴',
        "lucky_color": 'プラチナホワイト',
        "color_code": '#fafaff',
        "lyrics_snippet": "That's my life, is a beautiful galaxy / 堂々と進め",
        "youtube_query": 'IVE I AM',
    },
    {
        "id": 41,
        "title": 'Shake It Off',
        "artist": 'Taylor Swift',
        "genre": 'western_pop',
        "moods": ['energy', 'happy'],
        "description": '他人の目を気にせず、ネガティブな意見は笑い飛ばそうという応援歌。今日は余計な悩みはスルーして、あなたらしく羽ばたく日です。',
        "lucky_item": 'カラフルなキーホルダー',
        "lucky_color": 'スカイブルー',
        "color_code": '#87ceeb',
        "lyrics_snippet": "Heartbreakers gonna break... I'm just gonna shake, shake / Shake it off!",
        "youtube_query": 'Taylor Swift Shake It Off',
    },
    {
        "id": 42,
        "title": 'Ocean Eyes',
        "artist": 'Billie Eilish',
        "genre": 'western_pop',
        "moods": ['calm', 'emotional'],
        "description": '幻想的で透き通るようなボーカル。自分の中の繊細な感情を優しく労わる日。夜風にあたりながら月を眺めると、心が静まります。',
        "lucky_item": 'シルバーの指輪',
        "lucky_color": 'インディゴブルー',
        "color_code": '#4b0082',
        "lyrics_snippet": "I've been watching you for some time / Can't stop staring at those ocean eyes",
        "youtube_query": 'Billie Eilish Ocean Eyes',
    },
    {
        "id": 43,
        "title": 'Levitating',
        "artist": 'Dua Lipa',
        "genre": 'western_pop',
        "moods": ['happy', 'energy'],
        "description": '宇宙をドライブするようなレトロフューチャー・ポップ。今日は軽やかなノリで進むと、素晴らしい発見や幸運に出会える予感です。',
        "lucky_item": '星のキーチャーム',
        "lucky_color": 'スペースシルバー',
        "color_code": '#c0c0c0',
        "lyrics_snippet": "I got you, moonlight, you're my starlight / I need you all night, come on, levitate with me",
        "youtube_query": 'Dua Lipa Levitating',
    },
    {
        "id": 44,
        "title": 'Just the Way You Are',
        "artist": 'Bruno Mars',
        "genre": 'western_pop',
        "moods": ['happy', 'emotional'],
        "description": 'あなたのありのままの美しさを全力で肯定する至高のラブレター。自信をなくしそうなときは、自分の良いところを3つ書き出してみて。',
        "lucky_item": 'リップバーム',
        "lucky_color": 'ローズピンク',
        "color_code": '#ff66cc',
        "lyrics_snippet": "When I see your face, there's not a thing that I would change / 'Cause you're amazing, just the way you are",
        "youtube_query": 'Bruno Mars Just the Way You Are',
    },
    {
        "id": 45,
        "title": 'Shape of You',
        "artist": 'Ed Sheeran',
        "genre": 'western_pop',
        "moods": ['happy', 'calm'],
        "description": '心地よいマリンバのループとキャッチーな恋の駆け引き。日常のリズムを軽やかに刻みながら、お気に入りのカフェでリラックスする時間に幸運が宿ります。',
        "lucky_item": 'コーヒーマグ',
        "lucky_color": 'テラコッタオレンジ',
        "color_code": '#e2725b',
        "lyrics_snippet": "I'm in love with the shape of you / We push and pull like a magnet do",
        "youtube_query": 'Ed Sheeran Shape of You',
    },
    {
        "id": 46,
        "title": 'Blinding Lights',
        "artist": 'The Weeknd',
        "genre": 'western_pop',
        "moods": ['energy', 'focus'],
        "description": '80年代風シンセポップの疾走感。都会的な夜のドライブや深夜の作業にぴったり。集中力が最高潮に高まり、作業を爆速で終わらせられる日です。',
        "lucky_item": 'サングラス（スクエア型）',
        "lucky_color": 'ネオンレッド',
        "color_code": '#ff073a',
        "lyrics_snippet": "I said, ooh, I'm blinded by the lights / No, I can't sleep until I feel your touch",
        "youtube_query": 'The Weeknd Blinding Lights',
    },
    {
        "id": 47,
        "title": 'As It Was',
        "artist": 'Harry Styles',
        "genre": 'western_pop',
        "moods": ['happy', 'calm'],
        "description": '軽快なビートの裏に少しの切なさを滲ませる、インディー・ポップ。時の流れや変化を受け入れ、今日という日を柔軟に楽しむことが幸運を引き寄せます。',
        "lucky_item": 'レコードプレーヤー（またはレトロな雑貨）',
        "lucky_color": 'ペールブルー',
        "color_code": '#afeeee',
        "lyrics_snippet": "In this world, it's just us / You know it's not the same as it was",
        "youtube_query": 'Harry Styles As It Was',
    },
    {
        "id": 48,
        "title": 'drivers license',
        "artist": 'Olivia Rodrigo',
        "genre": 'western_pop',
        "moods": ['emotional'],
        "description": '失恋の痛みと未練をエモーショナルに歌い上げる大ヒット曲。心の中の悲しみや葛藤を否定せず、涙とともに全て吐き出すことで、心のデトックスができる日です。',
        "lucky_item": 'ティッシュペーパー（高級タイプ）',
        "lucky_color": 'レイニーグレー',
        "color_code": '#a9a9a9',
        "lyrics_snippet": "And I know we weren't perfect but I've never felt this way for no one",
        "youtube_query": 'Olivia Rodrigo drivers license',
    },
    {
        "id": 49,
        "title": 'Peaches',
        "artist": 'Justin Bieber ft. Daniel Caesar, Giveon',
        "genre": 'western_pop',
        "moods": ['calm', 'happy'],
        "description": '極上のチルでメロウなポップ・R&B。心地よい風を感じながら、のんびりとお気に入りの音楽を聴いて過ごす、穏やかで上質な一日になります。',
        "lucky_item": 'ピーチティー',
        "lucky_color": 'ピーチシャーベット',
        "color_code": '#ffdab9',
        "lyrics_snippet": 'I get my peaches out in Georgia / I get my weed from California',
        "youtube_query": 'Justin Bieber Peaches',
    },
    {
        "id": 50,
        "title": 'Flowers',
        "artist": 'Miley Cyrus',
        "genre": 'western_pop',
        "moods": ['happy', 'energy'],
        "description": '自立と自己愛を力強く宣言するミドルテンポのポップ。誰かに幸せにしてもらうのを待つのではなく、自分で自分を精一杯もてなす素敵な一日にしましょう！',
        "lucky_item": '花束（自分用に購入）',
        "lucky_color": 'マリーゴールドゴールド',
        "color_code": '#e5a93b',
        "lyrics_snippet": 'I can buy myself flowers / Write my name in the sand',
        "youtube_query": 'Miley Cyrus Flowers',
    },
    {
        "id": 51,
        "title": 'Easy On Me',
        "artist": 'Adele',
        "genre": 'western_pop',
        "moods": ['emotional', 'calm'],
        "description": '過去の選択を振り返り、自分を許すための壮大なピアノ・バラード。完璧を求めすぎず、自分のペースで進むことを自分に許可してあげてください。',
        "lucky_item": '温かい毛布',
        "lucky_color": 'チャコールブラウン',
        "color_code": '#3e2723',
        "lyrics_snippet": 'Go easy on me, baby / I was still a child',
        "youtube_query": 'Adele Easy On Me',
    },
    {
        "id": 52,
        "title": 'Viva La Vida',
        "artist": 'Coldplay',
        "genre": 'western_pop',
        "moods": ['energy', 'emotional'],
        "description": '壮麗なストリングスと、王の栄枯盛衰を歌う歴史的な名曲。大きな視点で自分の人生を眺め、新たなビジョンや志を心に抱くのにふさわしい日です。',
        "lucky_item": '絵画のポストカード',
        "lucky_color": 'バロックゴールド',
        "color_code": '#c5a059',
        "lyrics_snippet": 'I hear Jerusalem bells a-ringing / Roman Cavalry choirs are singing',
        "youtube_query": 'Coldplay Viva La Vida',
    },
    {
        "id": 53,
        "title": 'Cruel Summer',
        "artist": 'Taylor Swift',
        "genre": 'western_pop',
        "moods": ['energy', 'happy'],
        "description": '切なさと狂おしいほどの情熱が混ざり合う、最高潮のシンセ・ポップ。感情が揺さぶられるような刺激的な出来事や、情熱的な対話の予感。',
        "lucky_item": 'アイスレモネード',
        "lucky_color": 'サンセットイエロー',
        "color_code": '#fcd116',
        "lyrics_snippet": "It's a cruel summer / With you",
        "youtube_query": 'Taylor Swift Cruel Summer',
    },
    {
        "id": 54,
        "title": 'Señorita',
        "artist": 'Shawn Mendes & Camila Cabello',
        "genre": 'western_pop',
        "moods": ['happy', 'calm'],
        "description": 'セクシーでスモーキーなラテン・ポップのデュエット。少しミステリアスな雰囲気を漂わせることで、異性や友人からの注目度がアップする日です。',
        "lucky_item": 'ミントタブレット',
        "lucky_color": 'オリーブグリーン',
        "color_code": '#808000',
        "lyrics_snippet": "I love it when you call me Señorita / I wish I could pretend I didn't need ya",
        "youtube_query": 'Shawn Mendes Camila Cabello Senorita',
    },
    {
        "id": 55,
        "title": 'Bad Romance',
        "artist": 'Lady Gaga',
        "genre": 'western_pop',
        "moods": ['energy'],
        "description": '破壊的でアヴァンギャルドなダンスアンセム。あなたの強烈な個性を隠さず、前衛的なクリエイティビティを発揮する日。妥協のない挑戦が実を結びます。',
        "lucky_item": 'レザーブーツ',
        "lucky_color": 'ダークブラック',
        "color_code": '#111111',
        "lyrics_snippet": "I want your ugly, I want your disease / I want your everything as long as it's free",
        "youtube_query": 'Lady Gaga Bad Romance',
    },
    {
        "id": 56,
        "title": 'Firework',
        "artist": 'Katy Perry',
        "genre": 'western_pop',
        "moods": ['energy', 'happy'],
        "description": 'あなたの内に秘めた無限の可能性を花火のように咲かせようという賛歌。今日、あなたが主役となってスポットライトを浴びる瞬間が訪れます！',
        "lucky_item": 'キラキラした筆記用具',
        "lucky_color": 'レインボーカラー',
        "color_code": '#ff00ff',
        "lyrics_snippet": "Baby, you're a firework / Come on, let your colors burst",
        "youtube_query": 'Katy Perry Firework',
    },
    {
        "id": 57,
        "title": 'Sugar',
        "artist": 'Maroon 5',
        "genre": 'western_pop',
        "moods": ['happy'],
        "description": '甘くてファンキーなポップソング。今日は周囲の人に対して砂糖のように甘く親切に接すると、その何倍ものハッピーがあなたに戻ってきます。',
        "lucky_item": 'ドーナツなどのスイーツ',
        "lucky_color": 'キャンディピンク',
        "color_code": '#ffb6c1',
        "lyrics_snippet": "Sugar, yes please / Won't you come and put it down on me",
        "youtube_query": 'Maroon 5 Sugar',
    },
    {
        "id": 58,
        "title": 'Snooze',
        "artist": 'SZA',
        "genre": 'western_pop',
        "moods": ['calm', 'emotional'],
        "description": 'とろけるように心地よいR&B。大切な人と過ごす何気ない時間を噛みしめ、一瞬一瞬をスヌーズ（引き延ばし）したくなるような愛しさに包まれます。',
        "lucky_item": 'シルクの枕カバー',
        "lucky_color": 'ラベンダーグレー',
        "color_code": '#e6e6fa',
        "lyrics_snippet": "I can't lose when I'm with you / How can I snooze and miss the moment?",
        "youtube_query": 'SZA Snooze',
    },
    {
        "id": 59,
        "title": 'Espresso',
        "artist": 'Sabrina Carpenter',
        "genre": 'western_pop',
        "moods": ['happy', 'energy'],
        "description": '中毒性抜群のエスプレッソのように、あなたの魅力が誰かを夢中にさせてしまうポップチューン。フットワーク軽く、自信満々でいきましょう！',
        "lucky_item": 'エスプレッソコーヒー',
        "lucky_color": 'ダークブラウン',
        "color_code": '#3b2f2f',
        "lyrics_snippet": "Now he's thinkin' 'bout me every night, oh / Is it that sweet? I guess so",
        "youtube_query": 'Sabrina Carpenter Espresso',
    },
    {
        "id": 60,
        "title": 'bad guy',
        "artist": 'Billie Eilish',
        "genre": 'western_pop',
        "moods": ['energy', 'focus'],
        "description": '低音の効いたミニマルでダークなビート。ちょっといたずらっぽく、クールでミステリアスな立ち振る舞いが功を奏する日です。沈黙を武器にしましょう。',
        "lucky_item": '黒いキャップ',
        "lucky_color": 'ネオングリーン',
        "color_code": '#39ff14',
        "lyrics_snippet": "So you're a tough guy / Like it really rough guy / I'm that bad guy",
        "youtube_query": 'Billie Eilish bad guy',
    },
    {
        "id": 61,
        "title": "Don't Stop Me Now",
        "artist": 'Queen',
        "genre": 'rock',
        "moods": ['energy', 'happy'],
        "description": 'エネルギー爆発！どんな課題もハイスピードでクリアできる超好調な一日。心のままに走り抜けてください。',
        "lucky_item": '炭酸水',
        "lucky_color": 'フレアレッド',
        "color_code": '#ff3300',
        "lyrics_snippet": "Don't stop me now, 'cause I'm having a good time / I don't want to stop at all",
        "youtube_query": "Queen Don't Stop Me Now",
    },
    {
        "id": 62,
        "title": '前前前世 (Zenzenzense)',
        "artist": 'RADWIMPS',
        "genre": 'rock',
        "moods": ['energy', 'emotional'],
        "description": '時空を超えるほどの強烈な絆とスピード感。運命的なアイデアや、昔懐かしい友人からの連絡があるかもしれません。直感を信じて動いてみて。',
        "lucky_item": '腕時計',
        "lucky_color": 'コズミックネイビー',
        "color_code": '#000080',
        "lyrics_snippet": '君の前前前世から僕は 君を探し始めたよ',
        "youtube_query": 'RADWIMPS 前前前世',
    },
    {
        "id": 63,
        "title": 'Smells Like Teen Spirit',
        "artist": 'Nirvana',
        "genre": 'rock',
        "moods": ['energy'],
        "description": '90年代グランジの象徴。鬱屈としたエネルギーを爆発させて、現状の停滞を打ち破るための圧倒的な起爆剤になる一日です。',
        "lucky_item": 'ネルシャツ',
        "lucky_color": 'ダークオリーブ',
        "color_code": '#556b2f',
        "lyrics_snippet": "With the lights out, it's less dangerous / Here we are now, entertain us",
        "youtube_query": 'Nirvana Smells Like Teen Spirit',
    },
    {
        "id": 64,
        "title": 'In the End',
        "artist": 'Linkin Park',
        "genre": 'rock',
        "moods": ['energy', 'focus'],
        "description": 'ヘヴィなリフとエモーショナルなラップ／ボーカル。無駄に思える努力も、すべてはあなたの心の強さを鍛えるため。諦めない意志を固める日です。',
        "lucky_item": '黒いノート',
        "lucky_color": 'ガンメタルグレー',
        "color_code": '#2a2a2a',
        "lyrics_snippet": "I tried so hard and got so far / But in the end, it doesn't even matter",
        "youtube_query": 'Linkin Park In the End',
    },
    {
        "id": 65,
        "title": '完全感覚Dreamer',
        "artist": 'ONE OK ROCK',
        "genre": 'rock',
        "moods": ['energy'],
        "description": '世界に響く圧倒的な疾走ロック。誰に何を言われようと、自分の描く夢やヴィジョンを信じて突き進むエネルギーに満ちあふれる日です！',
        "lucky_item": 'リストバンド',
        "lucky_color": 'パッションレッド',
        "color_code": '#ff0000',
        "lyrics_snippet": '完全感覚Dreamerがボクの名さ / 誰が何を言おうと揺るがない',
        "youtube_query": 'ONE OK ROCK 完全感覚Dreamer',
    },
    {
        "id": 66,
        "title": "Livin' on a Prayer",
        "artist": 'Bon Jovi',
        "genre": 'rock',
        "moods": ['energy', 'happy'],
        "description": '困難に立ち向かうすべての人に捧ぐ、80年代アンセム。どんな苦境にあっても、「祈り（希望）」と「愛」があれば乗り越えられます！',
        "lucky_item": 'レザージャケット',
        "lucky_color": 'アンティークゴールド',
        "color_code": '#d4af37',
        "lyrics_snippet": "Woah, we're half way there / Woah, livin' on a prayer",
        "youtube_query": 'Bon Jovi Livin on a Prayer',
    },
    {
        "id": 67,
        "title": "Don't Look Back in Anger",
        "artist": 'Oasis',
        "genre": 'rock',
        "moods": ['emotional', 'calm'],
        "description": '美しく高らかな大合唱を生むUKロック。過去の後悔や怒りを洗い流し、晴れやかな気持ちで未来を見つめ直せる日。夕日を見ながら聴くのがおすすめ。',
        "lucky_item": 'サングラス（メタルフレーム）',
        "lucky_color": 'アンバーブラウン',
        "color_code": '#d2691e',
        "lyrics_snippet": "So Sally can wait, she knows it's too late as we're walking on by",
        "youtube_query": "Oasis Don't Look Back in Anger",
    },
    {
        "id": 68,
        "title": 'Uprising',
        "artist": 'Muse',
        "genre": 'rock',
        "moods": ['energy', 'focus'],
        "description": '闘志を呼び起こすスタジアム・ロック。理不尽な状況や自分自身の甘えに対して反旗を翻し、強い意志をもって立ち上がる日になります。',
        "lucky_item": 'スチール製のペン',
        "lucky_color": 'ダークプラチナ',
        "color_code": '#36454f',
        "lyrics_snippet": 'They will not force us / They will stop degrading us',
        "youtube_query": 'Muse Uprising',
    },
    {
        "id": 69,
        "title": 'Basket Case',
        "artist": 'Green Day',
        "genre": 'rock',
        "moods": ['energy', 'happy'],
        "description": '爆発的なポップパンクビート。ちょっとした焦りやパニックも、ユーモアを持って笑い飛ばし、軽やかに乗り越えられるハッピーな一日です。',
        "lucky_item": 'スケートボード（またはスニーカー）',
        "lucky_color": 'アシッドイエロー',
        "color_code": '#ccff00',
        "lyrics_snippet": 'Do you have the time to listen to me whine',
        "youtube_query": 'Green Day Basket Case',
    },
    {
        "id": 70,
        "title": 'Dani California',
        "artist": 'Red Hot Chili Peppers',
        "genre": 'rock',
        "moods": ['energy', 'focus'],
        "description": 'ヘヴィでファンキーなグルーヴロック。体の中から湧き上がるリズムを感じて、創造力や行動力をフルに解放できるエネルギッシュな日です。',
        "lucky_item": '辛いスパイス',
        "lucky_color": 'ホットチリレッド',
        "color_code": '#c21807',
        "lyrics_snippet": 'California, rest in peace / Simultaneous release',
        "youtube_query": 'Red Hot Chili Peppers Dani California',
    },
    {
        "id": 71,
        "title": 'リライト',
        "artist": 'ASIAN KUNG-FU GENERATION',
        "genre": 'rock',
        "moods": ['energy'],
        "description": '全身を揺さぶる激しいギターリフと咆哮。くすぶっている感情を一気に吹き飛ばし、自分自身の物語を「リライト（書き換え）」する強いパワーが得られます。',
        "lucky_item": '消しゴム付き鉛筆',
        "lucky_color": 'コバルトブルー',
        "color_code": '#0047ab',
        "lyrics_snippet": '消してリライトして くだらない超幻想を',
        "youtube_query": 'ASIAN KUNG-FU GENERATION リライト',
    },
    {
        "id": 72,
        "title": 'Bohemian Rhapsody',
        "artist": 'Queen',
        "genre": 'rock',
        "moods": ['emotional', 'energy'],
        "description": 'アカペラ、バラード、オペラ、ハードロックが融合した不朽の傑作。人生の喜怒哀楽をすべて包括したような、劇的で忘れられない一日が始まります。',
        "lucky_item": 'レトロな鍵',
        "lucky_color": 'アンティークブラス',
        "color_code": '#b5a642',
        "lyrics_snippet": "Mama, oooh / Didn't mean to make you cry",
        "youtube_query": 'Queen Bohemian Rhapsody',
    },
    {
        "id": 73,
        "title": 'Back In Black',
        "artist": 'AC/DC',
        "genre": 'rock',
        "moods": ['energy'],
        "description": '世界最強のギターリフ。シンプルかつ最高にタフなロックビート。逆境を跳ね除け、王座に返り咲くような不屈のスタミナが湧いてきます。',
        "lucky_item": '黒いTシャツ',
        "lucky_color": 'マットブラック',
        "color_code": '#1a1a1a',
        "lyrics_snippet": 'Back in black / I hit the sack',
        "youtube_query": 'ACDC Back In Black',
    },
    {
        "id": 74,
        "title": 'Creep',
        "artist": 'Radiohead',
        "genre": 'rock',
        "moods": ['emotional', 'calm'],
        "description": '自分の脆さや異端さを肯定してくれる、美しいオルタナティブ・ロック。完璧ではない自分自身を愛おしく思う、静かでエモーショナルな時間。',
        "lucky_item": '雨の音（または静かな部屋）',
        "lucky_color": 'フォググレー',
        "color_code": '#778899',
        "lyrics_snippet": "But I'm a creep / I'm a weirdo / What the hell am I doing here?",
        "youtube_query": 'Radiohead Creep',
    },
    {
        "id": 75,
        "title": 'Seven Nation Army',
        "artist": 'The White Stripes',
        "genre": 'rock',
        "moods": ['energy', 'focus'],
        "description": '極限まで削ぎ落とされたリフが放つ圧倒的な威圧感。何者にも邪魔させず、目の前のタスクや勝負事にひたすら集中して圧倒的な勝利を収める日です。',
        "lucky_item": '赤いマグカップ',
        "lucky_color": 'クリムゾンブラック',
        "color_code": '#3a0007',
        "lyrics_snippet": "A seven nation army couldn't hold me back",
        "youtube_query": 'The White Stripes Seven Nation Army',
    },
    {
        "id": 76,
        "title": 'The Pretender',
        "artist": 'Foo Fighters',
        "genre": 'rock',
        "moods": ['energy'],
        "description": '魂を揺さぶるストレートなオルタナティブ・ロック。他人の嘘や自分の弱さに妥協せず、真実を求めて全力で戦い抜くパワーがみなぎります。',
        "lucky_item": 'ダンベル',
        "lucky_color": 'スチールブルー',
        "color_code": '#4682b4',
        "lyrics_snippet": "What if I say I'm not like the others?",
        "youtube_query": 'Foo Fighters The Pretender',
    },
    {
        "id": 77,
        "title": 'ともに',
        "artist": 'WANIMA',
        "genre": 'rock',
        "moods": ['energy', 'happy'],
        "description": '太陽のような笑顔と圧倒的なプラスのパワー。どんなに辛い時も、仲間と共に笑い飛ばして進んでいける最強の応援歌です！',
        "lucky_item": 'カラフルなタオル',
        "lucky_color": 'シトラスグリーン',
        "color_code": '#adff2f',
        "lyrics_snippet": 'どれだけ過去が辛くて暗くても 昨日よりも笑顔で',
        "youtube_query": 'WANIMA ともに',
    },
    {
        "id": 78,
        "title": 'Space Sonic',
        "artist": 'ELLEGARDEN',
        "genre": 'rock',
        "moods": ['energy'],
        "description": 'エッジの効いたメロディックパンク。孤独や焦燥感を突き抜けて、宇宙の果てまで突き進むような高い解放感とスピード感が得られます。',
        "lucky_item": '星のステッカー',
        "lucky_color": 'ミッドナイトブルー',
        "color_code": '#000033',
        "lyrics_snippet": "I'm still alive / That's all I need to know",
        "youtube_query": 'ELLEGARDEN Space Sonic',
    },
    {
        "id": 79,
        "title": "Driver's High",
        "artist": "L'Arc~en~Ciel",
        "genre": 'rock',
        "moods": ['energy', 'happy'],
        "description": 'どこまでも加速していく圧倒的なドライブ感。エンジン全開で新しい世界へ飛び出す日。限界を超えた先にあるスリルを楽しんで！',
        "lucky_item": '車のキー（またはスマートキーチャーム）',
        "lucky_color": 'メタリックシルバー',
        "color_code": '#dcdcdc',
        "lyrics_snippet": '地平線に届くように 限界までぶっ飛ばしてくれ',
        "youtube_query": 'LArcenCiel Drivers High',
    },
    {
        "id": 80,
        "title": 'Welcome to the Black Parade',
        "artist": 'My Chemical Romance',
        "genre": 'rock',
        "moods": ['energy', 'emotional'],
        "description": '美しくドラマチックなパンク・オペラ。困難な状況にあっても、内なる誇りと信念を持って胸を張って行進し続けるような強靭な魂を呼び覚まします。',
        "lucky_item": 'ドラムスティック（またはペン）',
        "lucky_color": 'ダークパープルブラック',
        "color_code": '#1c0d22',
        "lyrics_snippet": "We'll carry on, we'll carry on / And though you're dead and gone, believe me",
        "youtube_query": 'My Chemical Romance Welcome to the Black Parade',
    },
    {
        "id": 81,
        "title": '24K Magic',
        "artist": 'Bruno Mars',
        "genre": 'rnb',
        "moods": ['happy', 'energy'],
        "description": '圧倒的にゴージャスでファンキーなR&B。今日のあなたは自信に満ちあふれ、周囲を明るく照らす存在です。自分へのご褒美を忘れずに！',
        "lucky_item": 'ゴールドのアクセサリー',
        "lucky_color": 'シャンパンゴールド',
        "color_code": '#f1c40f',
        "lyrics_snippet": 'Tonight I just want to take you higher / Throw your hands up in the sky',
        "youtube_query": 'Bruno Mars 24K Magic',
    },
    {
        "id": 82,
        "title": 'Kill Bill',
        "artist": 'SZA',
        "genre": 'rnb',
        "moods": ['emotional', 'calm'],
        "description": 'チルでメロウなR&Bビート。複雑な感情をそっと肯定してくれるような、リラックスしたプライベートタイムを持つと運気が高まります。',
        "lucky_item": 'グリーンスムージー',
        "lucky_color": 'セージグリーン',
        "color_code": '#8fbc8f',
        "lyrics_snippet": "I might kill my ex, not the best idea / His new girlfriend's next, how'd I get here?",
        "youtube_query": 'SZA Kill Bill',
    },
    {
        "id": 83,
        "title": 'Bad Habit',
        "artist": 'Steve Lacy',
        "genre": 'rnb',
        "moods": ['calm', 'emotional'],
        "description": 'インディーR&Bの最高峰。ノスタルジックで甘酸っぱい感情に浸りながら、自分の本音をゆっくりと大切に振り返りたい一日です。',
        "lucky_item": '古着のシャツ',
        "lucky_color": 'アプリコットオレンジ',
        "color_code": '#ffb07c',
        "lyrics_snippet": 'I wish I knew, I wish I knew you wanted me / Oh, what you do to me?',
        "youtube_query": 'Steve Lacy Bad Habit',
    },
    {
        "id": 84,
        "title": "If I Ain't Got You",
        "artist": 'Alicia Keys',
        "genre": 'rnb',
        "moods": ['emotional', 'calm'],
        "description": 'ソウルフルな歌声と美しいピアノ。富や名声よりも、真の愛や信頼関係の尊さを再確認できる日です。大切な人との対話を最優先に。',
        "lucky_item": 'アンティークな鍵',
        "lucky_color": 'コッパー',
        "color_code": '#b87333',
        "lyrics_snippet": "Some people want it all / But I don't want nothing at all / If it ain't got you, baby",
        "youtube_query": "Alicia Keys If I Ain't Got You",
    },
    {
        "id": 85,
        "title": 'Best Part',
        "artist": 'Daniel Caesar ft. H.E.R.',
        "genre": 'rnb',
        "moods": ['calm', 'happy'],
        "description": 'とろけるようなアコースティック・ソウル。朝の柔らかな光の中で、淹れたてのコーヒーを飲むような心地よく温かい幸運に満じる日です。',
        "lucky_item": 'カフェラテ',
        "lucky_color": 'ウォームベージュ',
        "color_code": '#f5f5dc',
        "lyrics_snippet": "You're the coffee that I need in the morning / You're my sunshine in the rain",
        "youtube_query": 'Daniel Caesar Best Part',
    },
    {
        "id": 86,
        "title": 'Starboy',
        "artist": 'The Weeknd ft. Daft Punk',
        "genre": 'rnb',
        "moods": ['focus', 'energy'],
        "description": 'ダークで近未来的なネオソウル。エッジの効いた自己表現と自信が成功の鍵。周りの雑音を消し去り、スターのように孤高に光る日です。',
        "lucky_item": '黒いレザースニーカー',
        "lucky_color": 'ネオンブルーブラック',
        "color_code": '#001a33',
        "lyrics_snippet": "Look what you've done / I'm a motherfucking starboy",
        "youtube_query": 'The Weeknd Starboy',
    },
    {
        "id": 87,
        "title": 'Thinkin Bout You',
        "artist": 'Frank Ocean',
        "genre": 'rnb',
        "moods": ['calm', 'emotional'],
        "description": '切なく揺らめくインディー・オルタナティブR&B。静かに自分の内省や想い出に浸り、感情のグラデーションを味わうのに最適な一日。',
        "lucky_item": 'お気に入りのクッション',
        "lucky_color": 'スモーキーローズ',
        "color_code": '#d6c4c4',
        "lyrics_snippet": "No, I don't like you, I just think about you / Every second, every minute",
        "youtube_query": 'Frank Ocean Thinkin Bout You',
    },
    {
        "id": 88,
        "title": 'Focus',
        "artist": 'H.E.R.',
        "genre": 'rnb',
        "moods": ['calm', 'focus'],
        "description": '繊細でメロウなギターとハスキーな歌声。身の回りの大切な人、あるいは本当にやるべき仕事に「フォーカス」することで、劇的に運気が高まります。',
        "lucky_item": 'アイウェア（メガネ）',
        "lucky_color": 'クリアオリーブ',
        "color_code": '#bab86c',
        "lyrics_snippet": 'Can you focus on me? / Baby, let me know',
        "youtube_query": 'HER Focus',
    },
    {
        "id": 89,
        "title": 'Halo',
        "artist": 'Beyoncé',
        "genre": 'rnb',
        "moods": ['emotional', 'energy'],
        "description": '心を揺さぶる圧倒的なソウルパワー。あなたのまとうオーラ（後光）が周囲の人を魅了し、自然と人が集まりリスペクトされる輝かしい一日です。',
        "lucky_item": 'クリスタルの置物',
        "lucky_color": 'オーロラホワイト',
        "color_code": '#f0f8ff',
        "lyrics_snippet": "Everywhere I'm looking now / I'm surrounded by your embrace / Baby, I can see your halo",
        "youtube_query": 'Beyonce Halo',
    },
    {
        "id": 90,
        "title": 'All of Me',
        "artist": 'John Legend',
        "genre": 'rnb',
        "moods": ['emotional'],
        "description": '極限までシンプルなピアノと圧倒的な歌唱力の愛の讃歌。弱さも含めた自分や相手のすべてを受け入れることで、深い結びつきが得られる日。',
        "lucky_item": '赤いキャンドル',
        "lucky_color": 'ディープマホガニー',
        "color_code": '#4a0404',
        "lyrics_snippet": 'Cause all of me loves all of you / Love your curves and all your edges',
        "youtube_query": 'John Legend All of Me',
    },
    {
        "id": 91,
        "title": 'Leave the Door Open',
        "artist": 'Silk Sonic',
        "genre": 'rnb',
        "moods": ['happy', 'calm'],
        "description": '70年代ソウルの黄金期を完璧に現代に蘇らせたスイートな曲。ロマンチックで少しユーモラスな出会いや、心がとろけるような時間がありますように。',
        "lucky_item": 'レコード型のキーホルダー',
        "lucky_color": 'マスタードイエロー',
        "color_code": '#e1ad01',
        "lyrics_snippet": "I'mma leave the door open / Hoping that you feel the way I do",
        "youtube_query": 'Silk Sonic Leave the Door Open',
    },
    {
        "id": 92,
        "title": 'Location',
        "artist": 'Khalid',
        "genre": 'rnb',
        "moods": ['calm', 'happy'],
        "description": '若々しくチルなR&Bバイブス。小難しいことは抜きにして、自分の今いる「場所（現在地）」を存分に楽しむことで、リラックスした幸運が舞い込みます。',
        "lucky_item": 'スマートフォンの地図アプリ',
        "lucky_color": 'ミントブルーグレー',
        "color_code": '#b0c4de',
        "lyrics_snippet": "Send me your location, let's focus on communicating",
        "youtube_query": 'Khalid Location',
    },
    {
        "id": 93,
        "title": 'Good Days',
        "artist": 'SZA',
        "genre": 'rnb',
        "moods": ['calm', 'happy'],
        "description": '光が差し込むようなサイケデリックでドリーミーなR&B。これからは「もっと良い日（Good Days）」が来ると信じて、前向きに心を解放して過ごしましょう。',
        "lucky_item": 'ハーブティー',
        "lucky_color": 'ラベンダーピンク',
        "color_code": '#e6a8d7',
        "lyrics_snippet": 'I still wanna try for good days, good days / Always in my mind',
        "youtube_query": 'SZA Good Days',
    },
    {
        "id": 94,
        "title": 'Stay',
        "artist": 'Rihanna ft. Mikky Ekko',
        "genre": 'rnb',
        "moods": ['emotional', 'calm'],
        "description": 'ピアノとボーカルだけで紡ぐ、脆く儚いバラード。素直に自分の弱さを誰かに打ち明けたり、近くにいてほしいと伝えることで心がほどける日です。',
        "lucky_item": '木製コースター',
        "lucky_color": 'セピアブラウン',
        "color_code": '#704214',
        "lyrics_snippet": 'Not really sure how to feel about it / Something in the way you move',
        "youtube_query": 'Rihanna Stay',
    },
    {
        "id": 95,
        "title": 'Untitled (How Does It Feel)',
        "artist": "D'Angelo",
        "genre": 'rnb',
        "moods": ['calm'],
        "description": 'ネオ・ソウルの伝説的スロウジャム。深い安らぎと官能的なグルーヴ。夜の静寂の中で、自分の感情や体温をゆっくりと感じ取る癒やしの一日。',
        "lucky_item": 'マッサージオイル',
        "lucky_color": 'ココアブラック',
        "color_code": '#1f0f0f',
        "lyrics_snippet": 'How does it feel? / Tell me, how does it feel?',
        "youtube_query": 'DAngelo Untitled',
    },
    {
        "id": 96,
        "title": 'On & On',
        "artist": 'Erykah Badu',
        "genre": 'rnb',
        "moods": ['calm', 'focus'],
        "description": '気怠くも知的なジャジーR&B。周囲に流されず、自分だけの「インナー・ピース（内なる平和）」を最優先にすることで、頭がすっきりと冴え渡ります。',
        "lucky_item": 'ターバン（または帽子）',
        "lucky_color": 'アースカーキ',
        "color_code": '#8f9779',
        "lyrics_snippet": 'Oh on and on, and on and on / My drum goes dead',
        "youtube_query": 'Erykah Badu On and On',
    },
    {
        "id": 97,
        "title": "Isn't She Lovely",
        "artist": 'Stevie Wonder',
        "genre": 'rnb',
        "moods": ['happy', 'energy'],
        "description": '愛娘の誕生を祝う、生命力と歓喜に満ちた名曲。今日は身の回りにある小さな生命や愛おしい存在に対して、心から感謝したくなるハッピーな日です。',
        "lucky_item": '赤ちゃんやペットの画像',
        "lucky_color": 'デイジーイエロー',
        "color_code": '#fbe870',
        "lyrics_snippet": "Isn't she lovely? / Isn't she wonderful?",
        "youtube_query": 'Stevie Wonder Isnt She Lovely',
    },
    {
        "id": 98,
        "title": 'Doo Wop (That Thing)',
        "artist": 'Lauryn Hill',
        "genre": 'rnb',
        "moods": ['happy', 'energy'],
        "description": 'ヒップホップとクラシックソウルが完璧に融合した名盤。自分を安売りせず、自尊心を持って凛とした態度で過ごすことで、最高の運気が味方します。',
        "lucky_item": 'ゴールドのフープイヤリング',
        "lucky_color": 'アンティークブロンズ',
        "color_code": '#8c7853',
        "lyrics_snippet": "Girls, you know you'd better watch out / Some guys are only about that thing",
        "youtube_query": 'Lauryn Hill Doo Wop',
    },
    {
        "id": 99,
        "title": 'Yeah!',
        "artist": 'Usher ft. Lil Jon, Ludacris',
        "genre": 'rnb',
        "moods": ['energy', 'happy'],
        "description": '2000年代クランク＆R&Bのモンスターヒット。どんな憂鬱も吹き飛ばすキャッチーなシンセライン。今日は気分をぶち上げて楽しんだもの勝ちです！',
        "lucky_item": '光るバッジ',
        "lucky_color": 'ネオンブルー',
        "color_code": '#00ffff',
        "lyrics_snippet": 'Yeah, yeah, yeah / Usher baby',
        "youtube_query": 'Usher Yeah',
    },
    {
        "id": 100,
        "title": 'So Sick',
        "artist": 'Ne-Yo',
        "genre": 'rnb',
        "moods": ['emotional', 'calm'],
        "description": '切ないメロディと美しいハーモニー。失った恋への想いを断ち切れない不器用な自分を、音楽の優しさでそっと包み込んでくれる癒やしの一日です。',
        "lucky_item": 'メッセージカード',
        "lucky_color": 'アイスブルー',
        "color_code": '#f0f8ff',
        "lyrics_snippet": "And I'm so sick of love songs / So tired of tears",
        "youtube_query": 'NeYo So Sick',
    },
    {
        "id": 101,
        "title": 'Despacito',
        "artist": 'Luis Fonsi ft. Daddy Yankee',
        "genre": 'latin',
        "moods": ['happy', 'energy'],
        "description": '世界的なラテンの情熱的な大ヒット曲。太陽のように熱いエネルギーが注ぎ込む日です。音楽に合わせて体を軽く揺らすのがラッキーアクション。',
        "lucky_item": 'レモネード',
        "lucky_color": 'サンセットオレンジ',
        "color_code": '#ff5e00',
        "lyrics_snippet": 'Despacito / Quiero respirar tu cuello despacito',
        "youtube_query": 'Despacito Luis Fonsi',
    },
    {
        "id": 102,
        "title": 'Havana',
        "artist": 'Camila Cabello',
        "genre": 'latin',
        "moods": ['calm', 'emotional'],
        "description": '哀愁を帯びたピアノラインと魅力的なラテンリズム。少しミステリアスで大人な、知的な魅力を発揮できる一日になります。',
        "lucky_item": '赤いリップ',
        "lucky_color": 'ローズレッド',
        "color_code": '#c21e56',
        "lyrics_snippet": 'Havana, ooh na-na / Half of my heart is in Havana, ooh na-na',
        "youtube_query": 'Camila Cabello Havana',
    },
    {
        "id": 103,
        "title": 'Tití Me Preguntó',
        "artist": 'Bad Bunny',
        "genre": 'latin',
        "moods": ['energy', 'happy'],
        "description": '世界を席巻するレゲトンの王者。圧倒的にお祭り騒ぎなビート。今日はフットワークを軽くして、社交的になると面白いイベントが舞い込みます。',
        "lucky_item": '派手なスニーカー',
        "lucky_color": 'ネオンピンクオレンジ',
        "color_code": '#ff4f00',
        "lyrics_snippet": "Tití me preguntó si tengo mucha' novia'",
        "youtube_query": 'Bad Bunny Titi Me Pregunto',
    },
    {
        "id": 104,
        "title": "Hips Don't Lie",
        "artist": 'Shakira ft. Wyclef Jean',
        "genre": 'latin',
        "moods": ['energy', 'happy'],
        "description": '腰を揺らさずにはいられない魅惑のコロンビア・ポップ。今日は言葉での説明よりも、直感や体の感覚に従うほうがベストな選択ができます。',
        "lucky_item": 'ベルト（またはチャーム）',
        "lucky_color": 'サフランイエロー',
        "color_code": '#f4c430',
        "lyrics_snippet": "And I'm on tonight, you know my hips don't lie",
        "youtube_query": 'Shakira Hips Dont Lie',
    },
    {
        "id": 105,
        "title": 'DESPECHÁ',
        "artist": 'Rosalía',
        "genre": 'latin',
        "moods": ['happy', 'energy'],
        "description": 'モダン・フラメンコとラテンポップの歌姫による爽快な賛歌。ストレスや嫌な人間関係はすべて「DESPECHÁ（吹っ切る）」して飛び出そう！',
        "lucky_item": 'ココナッツウォーター',
        "lucky_color": 'ターコイズブルー',
        "color_code": '#30d5c8',
        "lyrics_snippet": 'Baby, no me llames, que yo estoy ocupada despechá',
        "youtube_query": 'Rosalia DESPECHA',
    },
    {
        "id": 106,
        "title": 'Mi Gente',
        "artist": 'J Balvin & Willy William',
        "genre": 'latin',
        "moods": ['energy'],
        "description": '中毒性抜群のミニマルなビート。言葉や文化の壁を越えて、世界中の「私の人々（みんな）」と繋がれるような圧倒的な団結力とパワーを感じる日。',
        "lucky_item": 'お揃いのステッカー',
        "lucky_color": 'エレクトリックグリーン',
        "color_code": '#00ff66',
        "lyrics_snippet": '¿Y dónde está mi gente? / Say yeah, yeah, yeah',
        "youtube_query": 'J Balvin Mi Gente',
    },
    {
        "id": 107,
        "title": 'PROVENZA',
        "artist": 'Karol G',
        "genre": 'latin',
        "moods": ['calm', 'happy'],
        "description": '穏やかでノスタルジックなレゲトンビート。忙しい日常から離れて、お気に入りのドライブコースやのんびりした時間を楽しむのに最適な一日です。',
        "lucky_item": 'サングラス（淡いカラー）',
        "lucky_color": 'パステルミント',
        "color_code": '#aaf0d1',
        "lyrics_snippet": 'Baby, ¿qué más? Hace rato que no sé de ti',
        "youtube_query": 'Karol G PROVENZA',
    },
    {
        "id": 108,
        "title": 'Bailando',
        "artist": 'Enrique Iglesias',
        "genre": 'latin',
        "moods": ['happy', 'energy'],
        "description": '心地よいアコースティックギターと高揚感のあるラテンビート。今日は心が躍るままに楽しめば、仕事も勉強も最高にスムーズに運びます。',
        "lucky_item": 'アイスキャンディ',
        "lucky_color": 'ルビーレッド',
        "color_code": '#e0115f',
        "lyrics_snippet": 'Yo quiero estar contigo, vivir contigo / Bailar contigo, tener contigo',
        "youtube_query": 'Enrique Iglesias Bailando',
    },
    {
        "id": 109,
        "title": "Livin' la Vida Loca",
        "artist": 'Ricky Martin',
        "genre": 'latin',
        "moods": ['energy', 'happy'],
        "description": '情熱と狂乱のラテン・ロック。ちょっと「クレイジー」なくらい大胆にアプローチすることで、停滞していた物事が一気にダイナミックに進みます。',
        "lucky_item": '激辛スナック',
        "lucky_color": 'スカーレットレッド',
        "color_code": '#ff2400',
        "lyrics_snippet": "Upside, inside out / She's livin' la vida loca",
        "youtube_query": 'Ricky Martin Livin la Vida Loca',
    },
    {
        "id": 110,
        "title": 'Hawái',
        "artist": 'Maluma',
        "genre": 'latin',
        "moods": ['emotional', 'happy'],
        "description": '切なくも踊れるトロピカル・ポップ。強がって見せるSNSの裏にある本音に寄り添うような、ロマンチックで少し胸がキュンとする時間。',
        "lucky_item": 'スマートフォンのカメラ',
        "lucky_color": 'コーラルオレンジ',
        "color_code": '#ff7f50',
        "lyrics_snippet": 'Deja de mentirte / La foto que subiste con él dizendo que era tu cielo',
        "youtube_query": 'Maluma Hawaii',
    },
    {
        "id": 111,
        "title": 'Gasolina',
        "artist": 'Daddy Yankee',
        "genre": 'latin',
        "moods": ['energy'],
        "description": 'レゲトンの代名詞とも言える超ハイテンションな爆速ビート。今日のあなたに必要なのは「ガソリン（情熱）」。フルスロットルで駆け抜けましょう！',
        "lucky_item": '赤い炭酸ドリンク',
        "lucky_color": 'ガソリンレッド',
        "color_code": '#e60012',
        "lyrics_snippet": 'A ella le gusta la gasolina / Dame más gasolina',
        "youtube_query": 'Daddy Yankee Gasolina',
    },
    {
        "id": 112,
        "title": 'telepatía',
        "artist": 'Kali Uchis',
        "genre": 'latin',
        "moods": ['calm', 'emotional'],
        "description": '浮遊感のあるドリーミーなラテンR&B。離れていても大切な人とテレパシーで繋がっているような、不思議な安心感とロマンに包まれる日です。',
        "lucky_item": 'パールのヘアクリップ',
        "lucky_color": 'パールホワイト',
        "color_code": '#eae6d8',
        "lyrics_snippet": 'Quién lo diría, que se podría / Hacer el amor por telepatía',
        "youtube_query": 'Kali Uchis telepatia',
    },
    {
        "id": 113,
        "title": 'Vivir Mi Vida',
        "artist": 'Marc Anthony',
        "genre": 'latin',
        "moods": ['happy', 'energy'],
        "description": '圧倒的なポジティブ・サルサ。「一度きりの人生、笑って、踊って、楽しもう！」という強力なメッセージが、あなたの今日を一気にハッピーにします。',
        "lucky_item": 'ひまわりの一輪挿し',
        "lucky_color": 'サルサイエロー',
        "color_code": '#ffd700',
        "lyrics_snippet": 'Voy a reír, voy a bailar / Vivir mi vida la la la la',
        "youtube_query": 'Marc Anthony Vivir Mi Vida',
    },
    {
        "id": 114,
        "title": 'Maria Maria',
        "artist": 'Santana ft. The Product G&B',
        "genre": 'latin',
        "moods": ['calm', 'happy'],
        "description": '伝説のラテンギタリストによる哀愁と情熱の傑作。大人の落ち着きと、隠れた情熱的な一面をアピールすると人間関係で魅力が倍増します。',
        "lucky_item": 'アコースティックの音源',
        "lucky_color": 'ブロンズブラウン',
        "color_code": '#cd7f32',
        "lyrics_snippet": 'Maria Maria / She reminds me of a West Side story',
        "youtube_query": 'Santana Maria Maria',
    },
    {
        "id": 115,
        "title": 'Sin Pijama',
        "artist": 'Becky G & Natti Natasha',
        "genre": 'latin',
        "moods": ['energy', 'happy'],
        "description": 'キャッチーで自信に満ちたアーバン・レゲトン。ガールズトークや親しい友人たちとの気取らない会話で、最高に盛り上がれるパワーが湧く日。',
        "lucky_item": 'お気に入りのルームウェア',
        "lucky_color": 'ディープサテンレッド',
        "color_code": '#800020',
        "lyrics_snippet": "Que no' quedamo' en la cama sin pijama",
        "youtube_query": 'Becky G Natti Natasha Sin Pijama',
    },
    {
        "id": 116,
        "title": 'Tacones Rojos',
        "artist": 'Sebastián Yatra',
        "genre": 'latin',
        "moods": ['happy', 'energy'],
        "description": '「赤いハイヒール」を履いて現れた彼女に一目惚れするような、明るく爽快なポップ。今日はロマンチックで弾けるような喜びに出会える予感！',
        "lucky_item": '赤い靴（または赤い小物）',
        "lucky_color": 'ルージュレッド',
        "color_code": '#e60033',
        "lyrics_snippet": 'Mi pedazo de sol / La niña de mis ojos / Tiene unos tacones rojos',
        "youtube_query": 'Sebastian Yatra Tacones Rojos',
    },
    {
        "id": 117,
        "title": 'Todo de Ti',
        "artist": 'Rauw Alejandro',
        "genre": 'latin',
        "moods": ['happy', 'calm'],
        "description": '80年代ディスコ風の爽やかでチルなレゲトン。あなたの好きな人の「すべて（Todo）」を優しく愛おしむような、心地よい風が吹く一日になります。',
        "lucky_item": 'お気に入りのヘアオイル',
        "lucky_color": 'アプリコットピンク',
        "color_code": '#ffb3a7',
        "lyrics_snippet": 'Me gusta todo de ti / Tu boca, tu juego, tu cuerpo',
        "youtube_query": 'Rauw Alejandro Todo de Ti',
    },
    {
        "id": 118,
        "title": 'Dákiti',
        "artist": 'Bad Bunny & Jhay Cortez',
        "genre": 'latin',
        "moods": ['energy', 'focus'],
        "description": '深海を漂うような未来的でダークなエレクトロ・レゲトン。集中力を研ぎ澄まし、クールに自分のミッションを完遂する力強い味方となります。',
        "lucky_item": '防水ワイヤレスイヤホン',
        "lucky_color": 'ネオンターコイズ',
        "color_code": '#00f5ff',
        "lyrics_snippet": "Y si tú me lo pide' / Yo me porto bonito",
        "youtube_query": 'Bad Bunny Dakiti',
    },
    {
        "id": 119,
        "title": "Don't Go Yet",
        "artist": 'Camila Cabello',
        "genre": 'latin',
        "moods": ['happy', 'energy'],
        "description": 'スパニッシュなクラップと情熱的なホーンセクション。楽しい時間がもっと続いてほしいと願うような、エネルギッシュで華やかなパーティーバイブス。',
        "lucky_item": '手鏡（装飾付き）',
        "lucky_color": 'ホットマゼンタ',
        "color_code": '#ff007f',
        "lyrics_snippet": "Don't go yet, don't go yet / Oh no, don't go yet",
        "youtube_query": 'Camila Cabello Dont Go Yet',
    },
    {
        "id": 120,
        "title": 'Danza Kuduro',
        "artist": 'Don Omar ft. Lucenzo',
        "genre": 'latin',
        "moods": ['energy', 'happy'],
        "description": '世界中のクラブや映画『ワイルド・スピード』で愛されたラテンアンセム。ビートに身を任せて、悩みごとを全部踊り飛ばして突き進む最強の一日！',
        "lucky_item": 'サングラス（大きめ）',
        "lucky_color": 'ゴールドイエロー',
        "color_code": '#ffd700',
        "lyrics_snippet": 'La mano arriba, cintura sola / Da la media volta, Danza Kuduro',
        "youtube_query": 'Don Omar Danza Kuduro',
    },
    {
        "id": 121,
        "title": '紅蓮華 (Gurenge)',
        "artist": 'LiSA',
        "genre": 'anime',
        "moods": ['energy'],
        "description": '力強い歌声が逆境に立ち向かう勇気をくれる曲。今日直面する壁は、あなたがさらに成長するためのチャンスです。自分の力を信じて！',
        "lucky_item": '赤いペン',
        "lucky_color": 'クリムゾンレッド',
        "color_code": '#dc143c',
        "lyrics_snippet": '強くなれる理由を知った 僕を連れて進め',
        "youtube_query": 'LiSA 紅蓮華',
    },
    {
        "id": 122,
        "title": '残酷な天使のテーゼ',
        "artist": '高橋洋子',
        "genre": 'anime',
        "moods": ['energy', 'happy'],
        "description": '限界を突破する神話的なエネルギー。あなたの隠れたポテンシャルが目覚める一日です。直感を信じて果敢に飛び立ちましょう！',
        "lucky_item": 'ホットコーヒー',
        "lucky_color": 'エヴァンゲリオンパープル',
        "color_code": '#502080',
        "lyrics_snippet": '残酷な天使のテーゼ 窓辺からやがて飛び立つ / 熱いパトスで思い出を裏切るなら',
        "youtube_query": '残酷な天使のテーゼ',
    },
    {
        "id": 123,
        "title": 'アイドル',
        "artist": 'YOASOBI',
        "genre": 'anime',
        "moods": ['energy', 'happy'],
        "description": '世界を席巻した究極のポップソング。圧倒的なカリスマ性と、他を寄せ付けない輝きを放つ日です。今日だけはあなたが世界の中心！',
        "lucky_item": 'キラキラしたスマホケース',
        "lucky_color": 'シャイニングピンク',
        "color_code": '#ff1493',
        "lyrics_snippet": '誰もが目を奪われていく 君は完璧で究極のアイドル',
        "youtube_query": 'YOASOBI アイドル',
    },
    {
        "id": 124,
        "title": '地球儀',
        "artist": '米津玄師',
        "genre": 'anime',
        "moods": ['emotional', 'calm'],
        "description": 'スタジオジブリ映画『君たちはどう生きるか』主題歌。静かに自分の生き方を問いかけ、一歩ずつ自分の道を作っていくための温かく力強い曲。',
        "lucky_item": '古い地球儀や地図',
        "lucky_color": 'アンティークグリーン',
        "color_code": '#556b2f',
        "lyrics_snippet": 'この道が続くのは 続けと願ったからだ',
        "youtube_query": '米津玄師 地球儀',
    },
    {
        "id": 125,
        "title": '廻廻奇譚',
        "artist": 'Eve',
        "genre": 'anime',
        "moods": ['energy', 'focus'],
        "description": '呪術をめぐるダークでスピーディーな世界観。自分の影や弱さに立ち向かい、打ち破る強い集中力と戦闘力が湧いてくる日です。',
        "lucky_item": '黒インクのボールペン',
        "lucky_color": '漆黒',
        "color_code": '#0f0f0f',
        "lyrics_snippet": '闇を祓って闇を祓って 夜の帳が下りたら合図だ',
        "youtube_query": 'Eve 廻廻奇譚',
    },
    {
        "id": 126,
        "title": 'Bling-Bang-Bang-Born',
        "artist": 'Creepy Nuts',
        "genre": 'anime',
        "moods": ['energy', 'happy'],
        "description": '中毒性抜群のジャージークラブ・ビート。常識外れの才能や実力で、周囲をあっと驚かせることができる爽快な一日になります！',
        "lucky_item": 'シュークリーム',
        "lucky_color": 'カスタードゴールド',
        "color_code": '#f5deb3',
        "lyrics_snippet": 'Bling-bang-bang, bling-bang-bang-born',
        "youtube_query": 'Creepy Nuts Bling Bang Bang Born',
    },
    {
        "id": 127,
        "title": 'GO!!!',
        "artist": 'FLOW',
        "genre": 'anime',
        "moods": ['energy', 'happy'],
        "description": 'アニメ『NARUTO』の不朽のオープニング。仲間とともに全力で走り出すような熱い青春エネルギー。目標に向けて「GO!!!」の合図を鳴らそう！',
        "lucky_item": 'お気に入りのスニーカー',
        "lucky_color": 'ビビッドオレンジ',
        "color_code": '#ff5f1f',
        "lyrics_snippet": 'We are Fighting Dreamers 高みを目指して',
        "youtube_query": 'FLOW GO',
    },
    {
        "id": 128,
        "title": 'イマジネーション',
        "artist": 'SPYAIR',
        "genre": 'anime',
        "moods": ['energy', 'happy'],
        "description": 'アニメ『ハイキュー!!』オープニング。どんなに劣勢でも、イマジネーション（想像力）と繋いだ手があれば、高く跳べると信じられる日です。',
        "lucky_item": 'スポーツタオル',
        "lucky_color": 'コートオレンジ',
        "color_code": '#f28500',
        "lyrics_snippet": '揺らせイマジネーション その先へと',
        "youtube_query": 'SPYAIR イマジネーション',
    },
    {
        "id": 129,
        "title": 'unravel',
        "artist": 'TK from 凛として時雨',
        "genre": 'anime',
        "moods": ['energy', 'emotional'],
        "description": 'アニメ『東京喰種』テーマ。激しく美しい悲鳴のようなボーカル。自分の中の葛藤や歪みをありのままに見つめ、全てを受け入れて進む日です。',
        "lucky_item": '冷たい水',
        "lucky_color": 'クリスタルクリア',
        "color_code": '#f0ffff',
        "lyrics_snippet": '揺れた歪んだ世界にだんだん僕は透き通って見えなくなって',
        "youtube_query": 'TK from 凛として時雨 unravel',
    },
    {
        "id": 130,
        "title": 'ピースサイン',
        "artist": '米津玄師',
        "genre": 'anime',
        "moods": ['energy', 'happy'],
        "description": 'アニメ『僕のヒーローアカデミア』テーマ。どんな傷や痛みも、最後には勝利のピースサインに変えてみせるというヒーローの決意が湧く日。',
        "lucky_item": '絆創膏',
        "lucky_color": 'ヒーローレッド',
        "color_code": '#ff2a2a',
        "lyrics_snippet": 'さらば掲げろ ピースサイン 転がっていくストーリーを',
        "youtube_query": '米津玄師 ピースサイン',
    },
    {
        "id": 131,
        "title": 'Magia',
        "artist": 'Kalafina',
        "genre": 'anime',
        "moods": ['emotional', 'focus'],
        "description": 'アニメ『魔法少女まどか☆マギカ』テーマ。ゴシックでミステリアスな旋律。運命の歯車を自分の手で回し、強い信念で奇跡を信じ抜く日。',
        "lucky_item": '懐中時計（または丸い小物）',
        "lucky_color": 'ダーククリムゾン',
        "color_code": '#4d0016',
        "lyrics_snippet": 'いつか君が瞳に灯す愛の光が 時を超えて',
        "youtube_query": 'Kalafina Magia',
    },
    {
        "id": 132,
        "title": 'Sparkle',
        "artist": 'RADWIMPS',
        "genre": 'anime',
        "moods": ['emotional', 'calm'],
        "description": '映画『君の名は。』テーマ。息をのむほど壮大で美しい時の流れ。運命的な出会いや、日常がきらきらと輝き出す奇跡的な瞬間に立ち会える日です。',
        "lucky_item": '望遠鏡（または星空を眺める）',
        "lucky_color": 'コズミックブルーゴールド',
        "color_code": '#001f3f',
        "lyrics_snippet": '運命だとか未来だとかって 言葉がどれだけ手を伸ばそうと届かない',
        "youtube_query": 'RADWIMPS スパークル',
    },
    {
        "id": 133,
        "title": '紅蓮の弓矢',
        "artist": 'Linked Horizon',
        "genre": 'anime',
        "moods": ['energy'],
        "description": 'アニメ『進撃の巨人』オープニング。限界を突き破り、自由を求めて獲物を狙うように戦う圧倒的覇気。目の前の壁を粉砕しましょう！',
        "lucky_item": 'ペン型カッター（または鍵）',
        "lucky_color": 'ミリタリーカーキ',
        "color_code": '#5b5d4b',
        "lyrics_snippet": '獲物を屠る《狩人》 湧き上がる《殺意》にその身を焦がしながら',
        "youtube_query": 'Linked Horizon 紅蓮の弓矢',
    },
    {
        "id": 134,
        "title": 'シュガーソングとビターステップ',
        "artist": 'UNISON SQUARE GARDEN',
        "genre": 'anime',
        "moods": ['happy', 'energy'],
        "description": 'アニメ『血界戦線』エンディング。甘くて苦い（シュガー＆ビター）カオスな日常を、軽やかにステップを踏んで笑い飛ばす最高のハッピーソング。',
        "lucky_item": 'ミントチョコ',
        "lucky_color": 'シュガーピンク',
        "color_code": '#ffb7d5',
        "lyrics_snippet": '超天変地異みたいな狂騒にも慣れてこんな日常を平和と見なす',
        "youtube_query": 'UNISON SQUARE GARDEN シュガーソングとビターステップ',
    },
    {
        "id": 135,
        "title": 'Simple And Clean',
        "artist": '宇多田ヒカル',
        "genre": 'anime',
        "moods": ['emotional', 'calm'],
        "description": 'ゲーム『キングダム ハーツ』テーマ。美しく幻想的で無垢な感情。シンプルで澄み切った心を取り戻すことで、複雑な問題が一気に解決します。',
        "lucky_item": 'ガラスのコップ',
        "lucky_color": 'クリアクリスタル',
        "color_code": '#e0ffff',
        "lyrics_snippet": "When you think of me, please don't kiss me / simple and clean is the way",
        "youtube_query": '宇多田ヒカル Simple And Clean',
    },
    {
        "id": 136,
        "title": 'Again',
        "artist": 'YUI',
        "genre": 'anime',
        "moods": ['energy', 'emotional'],
        "description": 'アニメ『鋼の錬金術師 FULLMETAL ALCHEMIST』テーマ。何度でもやり直し、自分の足で立ち上がる強い覚悟。過ちを恐れず、再挑戦する日です。',
        "lucky_item": '赤いフード付きの服',
        "lucky_color": 'アイアンレッド',
        "color_code": '#b22222',
        "lyrics_snippet": 'この想いを消してしまうには まだ早すぎるわ',
        "youtube_query": 'YUI Again',
    },
    {
        "id": 137,
        "title": 'シルエット',
        "artist": 'KANA-BOON',
        "genre": 'anime',
        "moods": ['energy', 'happy'],
        "description": 'アニメ『NARUTO -ナルト- 疾風伝』オープニング。忘れられない青春の面影。大事に抱えてきた想い出を背負って、迷わず未来へ駆け抜ける日。',
        "lucky_item": 'お気に入りのアルバム',
        "lucky_color": 'ノスタルジックイエロー',
        "color_code": '#eedc82',
        "lyrics_snippet": 'ひらりとひらり舞う 木の葉が揺れるように',
        "youtube_query": 'KANA-BOON シルエット',
    },
    {
        "id": 138,
        "title": '遥か彼方',
        "artist": 'ASIAN KUNG-FU GENERATION',
        "genre": 'anime',
        "moods": ['energy'],
        "description": '泥臭くも圧倒的にエモーショナルな疾走ロック。遥か彼方にある理想に向けて、今日からまた走り続ける意志を再確認できる日です。',
        "lucky_item": 'ヘッドバンド',
        "lucky_color": 'ダーククリムゾンブルー',
        "color_code": '#002a54',
        "lyrics_snippet": '生き急いで 擦りむいた心に 降る雨のように',
        "youtube_query": 'ASIAN KUNG-FU GENERATION 遥か彼方',
    },
    {
        "id": 139,
        "title": '深い森',
        "artist": 'Do As Infinity',
        "genre": 'anime',
        "moods": ['emotional', 'calm'],
        "description": 'アニメ『犬夜叉』エンディング。深く神秘的なアコースティックバラード。心の中の「深い森」に迷い込んだような時、静かに本質を見つけ出せる日です。',
        "lucky_item": '緑茶',
        "lucky_color": 'ディープフォレスト',
        "color_code": '#004026',
        "lyrics_snippet": '深い深い森の奥に 今もきっと置き去りにした心',
        "youtube_query": 'Do As Infinity 深い森',
    },
    {
        "id": 140,
        "title": 'Give a reason',
        "artist": '林原めぐみ',
        "genre": 'anime',
        "moods": ['energy', 'happy'],
        "description": 'アニメ『スレイヤーズNEXT』テーマ。どんな困難があっても、自分の生きる意味を求めて諦めずに立ち向かう、90年代最強の王道アニソンパワー！',
        "lucky_item": 'ブローチ',
        "lucky_color": 'ルビーゴールド',
        "color_code": '#c89d3c',
        "lyrics_snippet": '届けたいメロディがあるから どんな時も負けないでいられる',
        "youtube_query": '林原めぐみ Give a reason',
    },
    {
        "id": 141,
        "title": 'ジムノペディ 第1番 (Gymnopédie No. 1)',
        "artist": 'エリック・サティ',
        "genre": 'chill',
        "moods": ['calm', 'focus'],
        "description": '穏やかで美しいピアノソロ。今日は頑張るのを少しお休みして、静かに心を整える時間を持ちましょう。ハーブティーが心地よい眠りを誘います。',
        "lucky_item": '温かいハーブティー',
        "lucky_color": 'ミントグリーン',
        "color_code": '#98ff98',
        "lyrics_snippet": '静寂の中に流れる、ゆったりとした時の移ろいを感じて',
        "youtube_query": 'Erik Satie Gymnopedie No 1',
    },
    {
        "id": 142,
        "title": 'Energy Flow',
        "artist": '坂本龍一',
        "genre": 'chill',
        "moods": ['calm', 'focus'],
        "description": '心に深く染み入るピアノ旋律。過剰なプレッシャーから解放され、本来の自分のリズムを取り戻せる日です。深呼吸を3回行いましょう。',
        "lucky_item": '木漏れ日',
        "lucky_color": 'フォレストグリーン',
        "color_code": '#228b22',
        "lyrics_snippet": '静かに、ただ穏やかに流れるエネルギーに身を任せて',
        "youtube_query": 'Ryuichi Sakamoto Energy Flow',
    },
    {
        "id": 143,
        "title": 'Chill Lofi Beat',
        "artist": 'Lofi Girl Studio',
        "genre": 'chill',
        "moods": ['focus', 'calm'],
        "description": '心地よいビートとノスタルジックなメロディ。勉強や作業が驚くほど捗る一日です。ノイズを遮断して、自分の世界に没頭しましょう。',
        "lucky_item": 'お気に入りのノート',
        "lucky_color": 'ココアブラウン',
        "color_code": '#d2691e',
        "lyrics_snippet": 'ゆったりと流れるレコードの溝に、思考を泳がせて',
        "youtube_query": 'Lofi Girl study beat',
    },
    {
        "id": 144,
        "title": '月の光 (Clair de Lune)',
        "artist": 'クロード・ドビュッシー',
        "genre": 'chill',
        "moods": ['calm', 'focus'],
        "description": '静かな夜を彩るロマンチックなピアノの名曲。あなたの心に穏やかな波を立て、溜まった感情を美しく浄化してくれる夜になります。',
        "lucky_item": 'グラスに入ったお水',
        "lucky_color": 'ムーンライトブルー',
        "color_code": '#7f98b2',
        "lyrics_snippet": '夜空にそっと輝く、青白く優しい月の光を感じて',
        "youtube_query": 'Debussy Clair de Lune',
    },
    {
        "id": 145,
        "title": '月光ソナタ 第1楽章',
        "artist": 'ルートヴィヒ・ヴァン・ベートーヴェン',
        "genre": 'chill',
        "moods": ['calm', 'emotional'],
        "description": '静謐で深い悲しみを秘めたピアノの波。暗闇の美しさの中で、自分の本質や眠っていた本音と向き合える、厳かですがとても安らぐ時間です。',
        "lucky_item": 'クラシックのCD（またはレコード）',
        "lucky_color": 'ディープネイビーグレー',
        "color_code": '#1c2833',
        "lyrics_snippet": '静かに流れるピアノの打鍵音に、心の奥底を委ねて',
        "youtube_query": 'Beethoven Moonlight Sonata 1st movement',
    },
    {
        "id": 146,
        "title": 'Luv(sic) Part 3',
        "artist": 'Nujabes ft. Shing02',
        "genre": 'chill',
        "moods": ['calm', 'focus'],
        "description": '叙情的で美しいヒップホップビート。穏やかな日常への賛歌。机に向かう作業が驚くほど滑らかに進む、知的な幸運に満ちた日です。',
        "lucky_item": 'お気に入りの本',
        "lucky_color": 'セピアブラウン',
        "color_code": '#5c4033',
        "lyrics_snippet": "It's a beautiful thing to be alive, simple as that",
        "youtube_query": 'Nujabes Luv sic Part 3',
    },
    {
        "id": 147,
        "title": 'Awake',
        "artist": 'Tycho',
        "genre": 'chill',
        "moods": ['focus', 'calm'],
        "description": '心地よいアコースティックギターとデジタルビートの融合。朝の澄んだ空気の中で、頭がすっきりと目覚めて（Awake）やる気がみなぎる一日。',
        "lucky_item": 'お気に入りのコースター',
        "lucky_color": 'パステルオレンジ',
        "color_code": '#ffd6a5',
        "lyrics_snippet": '淡い朝の光とともに、ゆっくりと意識が目覚めていく',
        "youtube_query": 'Tycho Awake',
    },
    {
        "id": 148,
        "title": 'Kiara',
        "artist": 'Bonobo',
        "genre": 'chill',
        "moods": ['calm', 'focus'],
        "description": '神秘的で美しいストリングスのループとオーガニックなビート。あなたのインスピレーションを奥深くから呼び覚ます、静かに情熱的な日。',
        "lucky_item": '観葉植物',
        "lucky_color": 'アロエグリーン',
        "color_code": '#93c572',
        "lyrics_snippet": '複雑に絡み合う音のテクスチャが、心を静かに満たしていく',
        "youtube_query": 'Bonobo Kiara',
    },
    {
        "id": 149,
        "title": 'Weightless',
        "artist": 'Marconi Union',
        "genre": 'chill',
        "moods": ['calm'],
        "description": '科学的に「最もリラックス効果がある」と証明されたアンビエント曲。心拍数を穏やかに整え、究極の安らぎとリセットをもたらす日です。',
        "lucky_item": 'アロマディフューザー',
        "lucky_color": 'ミルキーホワイト',
        "color_code": '#fdfefe',
        "lyrics_snippet": '重力から解放されたかのように、身体と心が軽くなる',
        "youtube_query": 'Marconi Union Weightless',
    },
    {
        "id": 150,
        "title": 'An Ending (Ascent)',
        "artist": 'Brian Eno',
        "genre": 'chill',
        "moods": ['calm'],
        "description": '宇宙を漂うような神聖で壮大なアンビエント。悩みや葛藤がちっぽけなものに感じられ、魂が空へと上昇していくような癒やしを得られます。',
        "lucky_item": '広い空（またはベランダでの深呼吸）',
        "lucky_color": 'スカイブルーホワイト',
        "color_code": '#f0f8ff',
        "lyrics_snippet": 'どこまでも優しく広がる、音の宇宙に包まれて',
        "youtube_query": 'Brian Eno An Ending Ascent',
    },
    {
        "id": 151,
        "title": 'Summer',
        "artist": '久石譲',
        "genre": 'chill',
        "moods": ['happy', 'calm'],
        "description": '映画『菊次郎の夏』テーマ。誰もが体験したことがあるような、懐かしくきらきらとした日本の夏。今日一日を無邪気に楽しんで！',
        "lucky_item": '風鈴（または涼しい風）',
        "lucky_color": 'ひまわりレモン',
        "color_code": '#ffeb3b',
        "lyrics_snippet": '青空とひまわり畑、どこか懐かしいあの夏の記憶',
        "youtube_query": '久石譲 Summer',
    },
    {
        "id": 152,
        "title": 'River Flows in You',
        "artist": 'Yiruma',
        "genre": 'chill',
        "moods": ['emotional', 'calm'],
        "description": '優しく語りかけるようなニューエイジ・ピアノの名曲。あなたの心の中に静かに流れる「川（感情）」のせせらぎに耳を傾けてあげてください。',
        "lucky_item": '冷たいお水を入れたグラス',
        "lucky_color": 'クリアブルーウォーター',
        "color_code": '#e0f7fa',
        "lyrics_snippet": 'あなたの心の中に優しく寄り添う、穏やかな旋律の川',
        "youtube_query": 'Yiruma River Flows in You',
    },
    {
        "id": 153,
        "title": 'Nuvole Bianche',
        "artist": 'Ludovico Einaudi',
        "genre": 'chill',
        "moods": ['emotional', 'focus'],
        "description": '「白い雲」を意味する、息をのむほど美しいピアノ曲。流れる雲をただ眺めるように、思考を空っぽにして目の前のことに没頭できる日です。',
        "lucky_item": '白いティッシュ（またはハンカチ）',
        "lucky_color": 'クラウドホワイト',
        "color_code": '#f8f9f9',
        "lyrics_snippet": '大空を流れる白い雲のように、軽やかに移り変わる旋律',
        "youtube_query": 'Ludovico Einaudi Nuvole Bianche',
    },
    {
        "id": 154,
        "title": 'Tadow',
        "artist": 'FKJ & Masego',
        "genre": 'chill',
        "moods": ['calm', 'happy'],
        "description": '即興セッションから生まれた極上のネオ・ソウル／ジャズ。お洒落で小気味よい即興的なアイデアが、今日のピンチをチャンスに変えてくれます。',
        "lucky_item": 'お洒落なソックス',
        "lucky_color": 'マスタードブラウン',
        "color_code": '#b38b6d',
        "lyrics_snippet": 'Just like that, she had it all / Tadow',
        "youtube_query": 'FKJ Masego Tadow',
    },
    {
        "id": 155,
        "title": 'Avril 14th',
        "artist": 'Aphex Twin',
        "genre": 'chill',
        "moods": ['calm', 'focus'],
        "description": 'ピアノのペダル音や木製のきしみが温かい、極めてパーソナルなピアノ曲。大切なプライベート空間をそっと暖かく満たしてくれるような一日。',
        "lucky_item": 'お気に入りのペン',
        "lucky_color": 'チェリーウッド',
        "color_code": '#8b5a2b',
        "lyrics_snippet": 'あたたかな春の午後を思わせる、素朴で優しいピアノの響き',
        "youtube_query": 'Aphex Twin Avril 14th',
    },
    {
        "id": 156,
        "title": 'Time',
        "artist": 'Hans Zimmer',
        "genre": 'chill',
        "moods": ['emotional', 'focus'],
        "description": '映画『インセプション』テーマ。静かに始まり、地響きのように壮大になるストリングス。時間を超越したような圧倒的な集中と没頭が得られる日です。',
        "lucky_item": '砂時計（またはタイマー）',
        "lucky_color": 'ダークスチールグレー',
        "color_code": '#566573',
        "lyrics_snippet": '重厚に重なる音の波が、時の広がりを感じさせる',
        "youtube_query": 'Hans Zimmer Time',
    },
    {
        "id": 157,
        "title": '戦場のメリークリスマス (Merry Christmas Mr. Lawrence)',
        "artist": '坂本龍一',
        "genre": 'chill',
        "moods": ['emotional', 'calm'],
        "description": '永遠の名曲。美しくも悲しいオリエンタルなメロディが、あなたの魂に深く染み入り、今日の疲れをすべて溶かして優しい奇跡を運んできます。',
        "lucky_item": '温かい緑茶',
        "lucky_color": 'オリエンタルグリーン',
        "color_code": '#3b5323',
        "lyrics_snippet": '時空を超えて響き渡る、あの美しく切ない冬の旋律',
        "youtube_query": 'Ryuichi Sakamoto Merry Christmas Mr Lawrence',
    },
    {
        "id": 158,
        "title": 'Smile from U',
        "artist": 'Jinsang',
        "genre": 'chill',
        "moods": ['calm', 'focus'],
        "description": '温かいジャズピアノのサンプリングと心地よいドラムビート。あなたの心にそっと「笑顔（Smile）」を届けるような、優しく軽やかな作業日和。',
        "lucky_item": 'お気に入りのキーホルダー',
        "lucky_color": 'ライトアプリコット',
        "color_code": '#ffdab9',
        "lyrics_snippet": 'レコードの心地よいノイズが、あなたの集中を優しくサポートする',
        "youtube_query": 'Jinsang Smile from U',
    },
    {
        "id": 159,
        "title": 'Self Portrait',
        "artist": 'Chilly Gonzales',
        "genre": 'chill',
        "moods": ['calm', 'focus'],
        "description": '独創的で内省的ながら温かいピアノソロ。自分の内面を「セルフ・ポートレート（自画像）」のように客観的に見つめ、心を整理するのに最適な日。',
        "lucky_item": 'スケッチブックまたは無地ノート',
        "lucky_color": 'ナチュラルウッド',
        "color_code": '#e4c69b',
        "lyrics_snippet": '一音一音に紡ぎ出される、本当の自分の声を聴く時間',
        "youtube_query": 'Chilly Gonzales Self Portrait',
    },
    {
        "id": 160,
        "title": 'Halving the Compass',
        "artist": 'Helios',
        "genre": 'chill',
        "moods": ['calm', 'focus'],
        "description": '温かく広がるアコースティックギターとエレクトロニカ。迷いがある時に、心のコンパスがゆっくりと正しい方向を指し示してくれるような安心感があります。',
        "lucky_item": 'お気に入りの写真立て',
        "lucky_color": 'アンバーゴールド',
        "color_code": '#d4a373',
        "lyrics_snippet": '夕暮れ時の淡い光のように、優しく心を包み込むアンビエント',
        "youtube_query": 'Helios Halving the Compass',
    },
]
